version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - node/install-yarn:
          version: 1.22.4
      - aws-cli/setup
      - eb/setup

      - run:
          name: Front-End install
          command: |
            yarn frontend:install
      - run:
          name: Front-End Build
          command: |
            yarn frontend:build
      - run:
          name: Front-End Deploy
          command: |
            yarn frontend:deploy  
      - run:
          name: Back-End Install
          command: |
            yarn backend:install
      - run:
          name: Back-End Build
          command: |
            yarn backend:build
      - run:
          name: Back-End Deploy
          command: |
            yarn backend:deploy

workflows:
  build-deploy:
    jobs:
      - build:
         filters:
          branches:
            only:
              - master